/* profile.h — PacketScope camera-profile JSON -> cam_profile_t.
 *
 * Consumes the JSON that PacketScope (~/Projects/cardputerzero-packetscope)
 * writes per stream, so camemu can reproduce that camera. Dependency-free,
 * no dynamic allocation; the schema is fixed and generated by PacketScope. */
#ifndef CAMEMU_PROFILE_H
#define CAMEMU_PROFILE_H

typedef struct {
    /* control plane */
    char ctrl_proto[16];         /* rtsp / http-mjpeg / multicast */
    char url[256];
    char transport[192];
    char mcast_group[16];
    int  media_port;             /* -1 if absent */
    int  server_port;

    /* video format */
    char container[16];          /* mpeg2-tts / mpeg2-ts / mpeg2-ps / mpeg2-es / rtp-jpeg / raw-es */
    int  payload_type;
    unsigned ssrc;
    int  clock_hz;
    int  tts_unit;               /* 192, 0 if not TTS */
    int  video_pid;              /* -1 if absent */
    char codec[8];               /* H.264 / MPEG-2 / JPEG */
    char h264_profile[16];       /* "High" ... "" if n/a */
    int  level_x10;              /* 40 = L4.0, 0 if n/a */
    int  width, height;
    double fps;
    int  gop;
    long bitrate_kbps;
    /* exact-reproduction detail */
    int  aud, sei, inband_sps;   /* -1 unknown, 0/1 */
    char sps_b64[128];           /* base64 SPS NAL (sprop-parameter-sets), "" if none */
    char pps_b64[64];            /* base64 PPS NAL */
    char sdp[1024];              /* raw SDP body (\n-escaped), "" if none */
    int  cctv_profile;           /* -1 unknown, 0/1 */
    char src_ip[16], dst_ip[16];
    int  dst_port;
} cam_profile_t;

/* Parse a JSON document (NUL-terminated) into *out. 0 ok, -1 on malformed. */
int  cam_profile_parse(const char *json, cam_profile_t *out);
/* Load from a file path. 0 ok, -1 error. */
int  cam_profile_load(const char *path, cam_profile_t *out);
/* Human-readable dump to stdout (debugging / --dump). */
void cam_profile_dump(const cam_profile_t *p);

#endif /* CAMEMU_PROFILE_H */
